### PR TITLE
atomic-primops: Fix Setup.hs for current cabal versions

### PR DESCRIPTION
**Pull request by bgamari**
While trying to reproduce GHC #11444 on GHC master I found that this no longer
compiled due to improved encapsulation in the Cabal library.

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Oh bother, it looks like old versions of `Cabal` didn't have `mkVersion`. I suppose `custom-setup` is needed here to CPP-guard the import of `mkVersion`?

**Comment by bgamari** [comment]
@ezyang, would you say this is a time for `setup-depends`?

How recently was `mkVersion` introduced?

**Comment by ezyang** [comment]
Unfortunately, mkVersion was introduced at the same time Version was made more abstract. But honestly, why not just drop this version check, and mandate `cabal-version: >= 1.17` in the Cabal file?

**Comment by RyanGlScott** [comment]
> But honestly, why not just drop this version check, and mandate `cabal-version: >= 1.17` in the Cabal file?

I'd be OK with that, too. The obvious downside is that folks trying to build `atomic-primops` with older GHCs might have to upgrade their `cabal-install` installations, but that's certainly more doable than upgrading GHC itself.

@rrnewton: do you have a preference on whether we take the `custom-setup` approach or bump the minimum version bounds of `cabal-install`?

**Comment by RyanGlScott** [comment]
I talked to @rrnewton about this, and we came to the consensus that we should just increase the minimum required `cabal-version` to 1.18, which I did in eba9d198cf3bcf266b1a4a70f50a854a70309312. So now `atomic-primops` uses a simple `Setup`, so this has been obsoleted.

**Pull request closed without merging**
