### PR TITLE
New 7.10 primops

### PR DESCRIPTION
**Pull request by jberryman**
Okay, second try; this ought to work. Tested on 7.6.3, 7.8.3, and 7.10...

Still waiting on discussion in #43, but if you want to merge this here it is.

@tibbe you might be interested in some of the tests in atomic-primops/testing/Fetch.hs for inclusion in the GHC testsuite: fetchAndOrTest, and to a lesser extent fetchNandTest

### CODE REVIEW

**Comment by jberryman** [comment]
It looks like the CI failure is in the `atomic-primops-foreign` test suite. I didn't notice that it was using symlinks to also `#include CounterCommon.hs` from `atomic-primops`, which I'd moved. Sorry about that! 

I'm not sure I'll have more time on this this week, but let me know if you want the `atomic-primops-foreign` fix in here as well, or separately.

**Comment by jberryman** [comment]
Okay, I've fixed the `atomic-primops-foreign`package issues.

**Comment by jberryman** [comment]
@rrnewton do you think we can merge this?

**Comment by rrnewton** [comment]
Hi Brandom -- sorry I'm hosed with ICFP deadline.  But I trust you on this one so I'm just merging it blind.  Also, feel free to not wait for me if I'm too slow.

**Comment by jberryman** [comment]
Thanks, Ryan. Good luck with ICFP stuff!

**Pull request merged**
